<a href="https://colab.research.google.com/github/logee48/foml/blob/main/foml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [ ]:
import pandas as pd

df = pd.read_csv(r"/content/sample_data/california_housing_test.csv")
df.head(2)

# print(df.to_string())

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0

In [ ]:
df['latitude'].value_counts()
#count no of occurences and total count

34.02    35
34.06    33
34.05    32
34.07    31
34.11    31
         ..
37.08     1
39.19     1
38.21     1
36.55     1
34.68     1
Name: latitude, Length: 587, dtype: int64

In [ ]:
df.latitude.unique()
#display unique elements

array([37.37, 34.26, 33.78, 33.82, 36.33, 36.51, 38.63, 35.48, 38.4 ,
       34.08, 33.98, 35.85, 37.25, 32.97, 33.73, 33.81, 37.53, 38.69,
       34.21, 38.01, 37.75, 38.68, 34.07, 37.79, 33.28, 34.16, 37.76,
       33.99, 34.01, 33.91, 39.31, 34.55, 33.94, 34.  , 37.97, 33.92,
       33.93, 34.23, 36.2 , 32.77, 34.15, 34.09, 34.13, 33.17, 37.44,
       38.  , 37.7 , 35.97, 37.8 , 33.8 , 38.72, 37.33, 37.56, 37.23,
       40.87, 32.73, 37.69, 33.86, 34.04, 37.36, 39.5 , 37.49, 37.35,
       34.2 , 34.17, 37.99, 37.4 , 34.05, 34.25, 38.26, 37.68, 36.74,
       41.01, 37.62, 37.98, 33.87, 37.84, 36.64, 36.77, 38.42, 38.87,
       33.77, 34.02, 38.62, 32.8 , 36.54, 38.52, 34.27, 37.74, 40.77,
       33.63, 34.1 , 32.81, 37.34, 33.02, 37.3 , 38.55, 36.61, 33.84,
       37.73, 37.96, 34.03, 34.71, 36.75, 40.46, 36.95, 39.49, 32.75,
       39.28, 32.72, 37.54, 37.6 , 33.15, 37.72, 33.64, 32.79, 33.62,
       33.71, 34.94, 35.87, 34.19, 33.9 , 37.26, 38.64, 35.41, 39.06,
       34.28, 33.88, 37.55, 37.31, 33.06, 34.11, 32.83, 33.89, 32.86,
       38.95, 37.45, 39.11, 38.38, 37.87, 34.24, 37.28, 33.7 , 40.07,
       38.73, 37.14, 34.48, 38.34, 33.6 , 37.78, 38.51, 38.61, 37.43,
       33.72, 38.46, 34.18, 37.27, 35.91, 38.03, 39.79, 32.82, 39.14,
       33.07, 35.46, 37.39, 32.69, 36.3 , 34.22, 35.38, 33.85, 37.38,
       39.1 , 32.68, 37.95, 32.58, 32.87, 37.88, 37.64, 34.14, 33.43,
       38.98, 38.27, 38.44, 34.69, 37.59, 33.65, 34.12, 38.66, 35.35,
       38.23, 34.3 , 38.88, 33.96, 33.97, 32.98, 34.38, 37.66, 32.7 ,
       36.73, 38.35, 36.21, 38.78, 34.06, 32.91, 36.81, 32.93, 37.77,
       37.83, 40.78, 33.79, 39.15, 38.76, 33.61, 37.48, 40.31, 33.74,
       34.41, 36.68, 34.43, 36.22, 37.46, 37.85, 35.49, 38.97, 36.79,
       35.62, 39.13, 32.74, 33.13, 37.22, 34.98, 36.62, 33.08, 38.94,
       36.96, 35.39, 37.29, 32.71, 37.86, 39.52, 40.71, 36.56, 34.56,
       37.41, 38.67, 37.47, 33.95, 36.1 , 38.71, 34.35, 37.82, 36.82,
       36.78, 32.84, 38.56, 40.26, 39.75, 38.54, 33.66, 40.2 , 33.18,
       32.76, 38.28, 40.47, 36.09, 37.94, 39.07, 34.65, 36.06, 33.83,
       39.51, 32.61, 33.48, 32.64, 40.01, 32.85, 36.58, 38.47, 33.76,
       38.37, 41.23, 37.52, 34.29, 38.41, 33.69, 32.59, 36.42, 37.67,
       37.81, 36.23, 34.49, 34.42, 37.9 , 36.94, 36.9 , 39.7 , 36.52,
       36.59, 33.57, 37.92, 38.12, 37.71, 39.02, 37.42, 32.9 , 34.54,
       34.52, 33.68, 37.93, 36.98, 36.57, 38.24, 40.44, 36.14, 39.16,
       40.18, 36.35, 35.  , 39.2 , 32.66, 37.63, 37.58, 39.92, 39.22,
       35.14, 36.7 , 33.16, 40.75, 33.29, 40.95, 39.56, 37.04, 40.66,
       37.91, 37.65, 36.32, 40.15, 37.  , 35.3 , 40.57, 34.4 , 38.43,
       38.59, 34.58, 37.89, 38.9 , 33.75, 35.08, 36.72, 40.55, 38.31,
       38.58, 38.77, 35.65, 33.58, 38.33, 38.45, 36.37, 32.95, 38.29,
       40.61, 37.01, 36.76, 41.92, 36.13, 39.39, 39.01, 38.92, 38.96,
       38.14, 32.92, 37.32, 36.25, 33.21, 38.79, 40.48, 38.48, 33.01,
       33.09, 36.31, 39.32, 35.61, 33.1 , 34.31, 37.61, 37.05, 37.57,
       38.53, 36.91, 34.45, 33.14, 40.4 , 38.04, 36.39, 38.57, 32.57,
       39.63, 35.03, 36.19, 34.95, 33.19, 39.3 , 38.65, 33.51, 40.8 ,
       34.36, 39.24, 34.47, 34.5 , 36.99, 37.11, 35.26, 40.42, 35.06,
       34.62, 40.6 , 37.15, 38.11, 36.8 , 32.56, 34.87, 32.78, 33.42,
       37.19, 37.12, 36.63, 38.02, 36.65, 38.16, 39.72, 38.7 , 36.6 ,
       36.53, 36.97, 35.12, 37.13, 38.32, 39.66, 33.2 , 35.5 , 40.99,
       33.5 , 41.8 , 32.62, 39.76, 40.56, 35.27, 39.36, 39.12, 38.75,
       34.96, 33.12, 37.08, 39.19, 38.21, 36.55, 36.34, 36.38, 39.17,
       34.91, 36.89, 35.37, 34.44, 33.49, 40.39, 33.44, 40.45, 38.09,
       35.76, 36.71, 33.26, 34.32, 39.97, 39.46, 35.33, 33.67, 36.86,
       34.9 , 35.42, 36.16, 32.6 , 33.03, 35.74, 35.24, 40.59, 34.7 ,
       37.21, 35.17, 38.6 , 33.54, 38.5 , 39.23, 34.39, 38.22, 33.  ,
       34.37, 37.51, 39.77, 36.83, 40.79, 34.34, 39.25, 38.99, 36.12,
       37.24, 39.9 , 38.91, 38.39, 37.18, 38.93, 33.55, 35.29, 39.61,
       41.31, 39.67, 38.86, 34.51, 36.69, 38.15, 33.22, 40.17, 35.86,
       35.13, 38.13, 32.99, 39.74, 36.08, 39.93, 33.04, 40.72, 33.53,
       35.31, 39.27, 32.67, 34.86, 40.12, 40.97, 33.46, 39.44, 39.69,
       38.74, 38.25, 33.31, 39.21, 39.34, 35.32, 38.2 , 34.64, 34.53,
       36.44, 40.09, 37.07, 35.34, 36.85, 35.05, 38.05, 41.2 , 35.02,
       34.66, 39.8 , 36.92, 41.28, 38.49, 35.4 , 39.48, 32.96, 39.09,
       40.52, 38.1 , 41.54, 33.45, 39.35, 36.93, 34.46, 33.52, 33.11,
       35.15, 38.08, 40.64, 38.89, 38.81, 32.88, 35.51, 36.87, 41.63,
       35.36, 34.68])

In [ ]:
newone = df[df['latitude']==38.5]
print(newone)
#compare val

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1792    -121.53      38.5                17.0       3087.0           477.0
1896    -121.42      38.5                24.0       7740.0          1539.0
2816    -121.54      38.5                15.0       6093.0          1051.0

      population  households  median_income  median_house_value
1792      1365.0       495.0         6.4667            216800.0
1896      4333.0      1397.0         3.0250             87900.0
2816      2415.0       997.0         4.2075            183600.0

In [ ]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [ ]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [ ]:
test = df.isnull()
print(test)
# var = df[df['latitude']==True]
# print(var)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0         False     False               False        False           False
1         False     False               False        False           False
2         False     False               False        False           False
3         False     False               False        False           False
4         False     False               False        False           False
...         ...       ...                 ...          ...             ...
2995      False     False               False        False           False
2996      False     False               False        False           False
2997      False     False               False        False           False
2998      False     False               False        False           False
2999      False     False               False        False           False

      population  households  median_income  median_house_value
0          False       False          False               False
1          False       False          False               False
2          False       False          False               False
3          False       False          False               False
4          False       False          False               False
...          ...         ...            ...                 ...
2995       False       False          False               False
2996       False       False          False               False
2997       False       False          False               False
2998       False       False          False               False
2999       False       False          False               False

[3000 rows x 9 columns]